In [1]:
import numpy as np

## Numpy array

In [4]:
benim_listem = [10,20,30,40]

In [6]:
np.array(benim_listem) #listemi numpy dizisine çevirdim

array([10, 20, 30, 40])

In [7]:
type(np.array(benim_listem))

numpy.ndarray

In [8]:
matrix_listesi = [[10,20,30],[20,30,40],[20,40,50]]

In [9]:
matrix_listesi[1]

[20, 30, 40]

In [10]:
matrix_listesi[1][0]

20

In [11]:
np.array(matrix_listesi)

array([[10, 20, 30],
       [20, 30, 40],
       [20, 40, 50]])

## arange

In [13]:
list(range(0,10)) #liste oluşturduk

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
np.arange(0,10) #numpy dizisi oluşturdum

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [17]:
np.zeros(5) #içinde 5 tane 0 olan bir dizi oluştur

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,2)) #matrix olarak da yazılabilir

array([[0., 0.],
       [0., 0.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## linspace

In [25]:
np.linspace(0,20,6) #istenen aralıkta eşit farklarda dizi oluşturma

array([ 0.,  4.,  8., 12., 16., 20.])

In [27]:
np.linspace(0,10,5) #hepsi arasındaki fark eşit

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## eye

In [29]:
np.eye(3) #identity matrix oluşturur

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [31]:
np.random.randn(3) #standart normal dağılıma uygun veriler çıkarmaya çalışır
#randn bir numpy dizisi döndürüyor (tek değer değil)

array([ 1.42032929,  1.57369359, -0.2201575 ])

In [32]:
np.random.randn(4)

array([-0.42284858,  0.43566975,  1.16168952, -0.33922165])

In [33]:
np.random.randn(2,2)

array([[-0.60457391,  0.32459294],
       [ 1.91692669, -1.31075896]])

In [38]:
np.random.randint(1,10)
#verilen aralıkta bir integer getirir (yukarıda float döndürüyor)

6

In [40]:
np.random.randint(1,10,5) 
#int dizisi olarak 1 ve 10 arasından 5 tane rastgele rakam döndür

array([2, 8, 8, 1, 1])

In [49]:
benim_numpy_dizim = np.arange(12) 
#nump dizimi bir değişkene eşitledim

In [50]:
benim_numpy_dizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
benim_random_dizim = np.random.randint(0,100,12)

In [52]:
benim_random_dizim

array([22, 82, 28, 50, 48, 29, 32, 97, 82, 27, 81,  3])

## numpy dizi methodları

In [55]:
benim_numpy_dizim.reshape(4,3) #12 tane verim olduğu için 3*5 bir matrix yapamam
#reshape=yeniden şekillendir

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
benim_random_dizim.max() #en büyük elemanı bulur

97

In [59]:
benim_random_dizim.min() # en küçük elemanı bulur

3

In [60]:
benim_random_dizim.argmax() #en büyük elemanın indexini bulur

7

In [61]:
benim_random_dizim.argmin() #en küçük elemanın indexini bulur

11

In [63]:
benim_numpy_dizim.shape

(12,)

In [ ]:
ben