In [1]:
import numpy as np

In [3]:
benim_dizim = np.arange(0,15)

In [5]:
benim_dizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
benim_dizim[5]

5

In [8]:
benim_dizim[3:5] # 3. ve 5. index arasını getir

array([3, 4])

In [11]:
benim_dizim[3:5] = -2 #istenen elemanları değiştirdim

In [12]:
benim_dizim

array([ 0,  1,  2, -2, -2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
baska_dizi = np.arange(0,24)

In [15]:
baska_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
slicing_dizisi=baska_dizi[4:9]

In [25]:
slicing_dizisi

array([4, 5, 6, 7, 8])

In [26]:
baska_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
slicing_dizisi[:]=800

In [28]:
slicing_dizisi

array([800, 800, 800, 800, 800])

In [30]:
baska_dizi
#bu dizi de kendisinden ayrılan diziden etkilendi

array([  0,   1,   2,   3, 800, 800, 800, 800, 800,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [36]:
ornek_dizi = np.arange(0,24)

In [37]:
ornek_dizi_kopya = ornek_dizi.copy()

In [38]:
ornek_dizi_kopya_slicing= ornek_dizi_kopya[3:6]

In [39]:
ornek_dizi_kopya_slicing

array([3, 4, 5])

In [40]:
ornek_dizi_kopya_slicing[:]=800

In [41]:
ornek_dizi_kopya_slicing

array([800, 800, 800])

In [42]:
ornek_dizi_kopya

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [43]:
ornek_dizi #örnek dizi bu işlemden etkilenmedi ama kopyası etkilendi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [44]:
benim_listem= [[10,20,30],[20,30,40],[40,50,60]]

In [45]:
benim_matrix_dizim= np.array(benim_listem)

In [46]:
benim_matrix_dizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [47]:
benim_matrix_dizim[1,2]

40

In [48]:
benim_matrix_dizim[1][2]

40

In [52]:
benim_matrix_dizim[1:,2] #istenen yerler getirilebilir (slicing benzeri)

array([40, 60])

In [57]:
yeni_liste= [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]

In [58]:
yeni_matrix= np.array(yeni_liste)

In [59]:
yeni_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
yeni_matrix[[0,2,3]] 
#istediğim indexleri getirip matrix yapıyor
#index yerine liste veriyoruz aslında

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## operasyonlar

In [66]:
dizi_1= np.random.randint(1,100,20)

In [67]:
dizi_1

array([20, 30,  3, 84, 46, 90, 26, 83, 77, 82, 36, 90, 72, 26, 96, 17, 80,
       19, 71, 28])

In [68]:
dizi_1>24 #24den büyük olup olmadığına göre buleon olarak döndürüyor

array([False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True])

In [69]:
sonuc_dizisi= dizi_1 >24

In [70]:
sonuc_dizisi

array([False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True])

In [71]:
dizi_1

array([20, 30,  3, 84, 46, 90, 26, 83, 77, 82, 36, 90, 72, 26, 96, 17, 80,
       19, 71, 28])

In [73]:
dizi_1[sonuc_dizisi] #24den büyük olanları filtreledim

array([30, 84, 46, 90, 26, 83, 77, 82, 36, 90, 72, 26, 96, 80, 71, 28])

In [74]:
son_dizi= np.arange(0,24)

In [75]:
son_dizi+son_dizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [76]:
son_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [77]:
son_dizi*son_dizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [78]:
son_dizi-son_dizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [79]:
np.sqrt(son_dizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [80]:
np.max(son_dizi)

23

In [81]:
np.min(son_dizi)

0