In [1]:
isim=["melih","ata","kerem","samed","onat","mert","onur","tolga","burak","yasin","cagdas"]

In [2]:
len(isim)

11

In [3]:
import numpy as np

In [6]:
puan= np.random.randint(0,100,11)

In [7]:
puan

array([88,  6, 38, 74, 48, 73, 56, 74, 86, 84, 98])

In [11]:
puan[1]= 59

In [12]:
puan

array([88, 59, 38, 74, 48, 73, 56, 74, 86, 84, 98])

In [16]:
list(zip(isim,puan))

[('melih', 88),
 ('ata', 59),
 ('kerem', 38),
 ('samed', 74),
 ('onat', 48),
 ('mert', 73),
 ('onur', 56),
 ('tolga', 74),
 ('burak', 86),
 ('yasin', 84),
 ('cagdas', 98)]

In [20]:
puan_2 = np.random.randint(80,100,11)

In [21]:
puan_2

array([98, 99, 90, 87, 84, 98, 91, 82, 91, 94, 85])

In [24]:
ortalama= (puan + puan_2)/2

In [25]:
ortalama

array([93. , 79. , 64. , 80.5, 66. , 85.5, 73.5, 78. , 88.5, 89. , 91.5])

In [26]:
np.max(ortalama)

93.0

In [34]:
not_liste=list(zip(isim,ortalama))

In [43]:
can =sum(ortalama)/len(isim)

In [44]:
not_liste

[('melih', 93.0),
 ('ata', 79.0),
 ('kerem', 64.0),
 ('samed', 80.5),
 ('onat', 66.0),
 ('mert', 85.5),
 ('onur', 73.5),
 ('tolga', 78.0),
 ('burak', 88.5),
 ('yasin', 89.0),
 ('cagdas', 91.5)]

In [45]:
ortalama>can

array([ True, False, False, False, False,  True, False, False,  True,
        True,  True])

In [46]:
type(ortalama)

numpy.ndarray

In [47]:
sonuc= ortalama>can

In [51]:
sonuc

array([ True, False, False, False, False,  True, False, False,  True,
        True,  True])

In [52]:
ortalama[sonuc]

array([93. , 85.5, 88.5, 89. , 91.5])

In [54]:
x=list(zip(isim,sonuc))

In [55]:
x

[('melih', True),
 ('ata', False),
 ('kerem', False),
 ('samed', False),
 ('onat', False),
 ('mert', True),
 ('onur', False),
 ('tolga', False),
 ('burak', True),
 ('yasin', True),
 ('cagdas', True)]

In [56]:
if not_liste[1]>

SyntaxError: invalid syntax (<ipython-input-56-066a53ae5c02>, line 1)